# Navigation links
nav:
  - title: "Writeups"
    url: /categories/writeups/
  - title: "Guides"
    url: /categories/guides/
  - title: "Projects"
    url: /categories/projects/
  - title: "Other Ramblings"
    url: /categories/other-ramblings/

title: Howell's Ramblings
description: A place for me to upload guides, projects, and other things I find interesting.
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

# Recommended settings
repository: chowell-it/ramblings
